version: "2"

run:
  timeout: 3m
  tests: false

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - unused

formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      rewrite-rules:
        - pattern: interface{}
          replacement: any

issues:
  max-issues-per-linter: 0
  max-same-issues: 0